# Generated by Django 3.2.8 on 2021-10-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_book_no_of_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('department', models.TextField()),
                ('matric_no', models.CharField(max_length=10)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
